logspout:
  restart: always
  environment:
    ROUTE_URIS: "${route_uri}"
    LOGSPOUT: 'ignore'
    DOMAINS: ${DOMAINS}
  volumes:
  - '/var/run/docker.sock:/var/run/docker.sock'
  external_links:
  - ${target_link}:${target_link_name}
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
  tty: true
  image: janeczku/logspout-logstash:v0.3.3
  stdin_open: true
