awselbv2:
  image: janeczku/external-dns-adv:latest-dev
  expose: 
   - 1000
  environment:
    ELBV2_AWS_ACCESS_KEY: ${ELBV2_AWS_ACCESS_KEY}
    ELBV2_AWS_SECRET_KEY: ${ELBV2_AWS_SECRET_KEY}
    ELBV2_AWS_REGION: ${ELBV2_AWS_REGION}
    ELBV2_AWS_VPCID: ${ELBV2_AWS_VPCID}
    ELBV2_USE_PRIVATE_IP: ${ELBV2_USE_PRIVATE_IP}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-dns"
    io.rancher.container.pull_image: always
