.catalog:
  name: ELB Application Load Balancer
  version: "v0.2.0-rancher1"
  description: "External LB service powered by AWS Elastic Load Balancing"
  minimum_rancher_version: v1.1.0
  questions:
    - variable: "ELBV2_AWS_ACCESS_KEY"
      label: "AWS Access Key ID"
      description: "Access key ID for your AWS account"
      type: "string"
      required: false
    - variable: "ELBV2_AWS_SECRET_KEY"
      label: "AWS Secret Access Key"
      description: "Secret access key for your AWS account"
      type: "string"
      required: false
    - variable: "ELBV2_AWS_REGION"
      label: "AWS Region (Optional)"
      description: "Region in which load balancers should be created in. Defaults to the region of the instance this service is running on."
      type: "string"
      required: false
    - variable: "ELBV2_AWS_VPCID"
      label: "AWS VPC ID (Optional)"
      description: "VPC in which load balancers should be created in. Defaults to the VPC of the instance this service is running on."
      type: "string"
      required: false
    - variable: "ELBV2_USE_PRIVATE_IP"
      label: "EC2 Private IP Lookup"
      description: "If your EC2 instances are registered in Rancher using their private IP addresses, then you must set this to true."
      required: true
      type: "boolean"
      default: false
    - variable: "ELBV2_CONNECTION_TIMEOUT"
      label: "Connection Idle Timeout"
      description: "The connection idle timeout in seconds for the load balancers. Valid range: 1-3600."
      type: "int"
      min: 1
      max: 3600
      default: 60
      required: true
    - variable: "ELBV2_ACCESS_LOGS_ENABLED"
      label: "Enable Access Logs"
      description: "Set this to 'true' to enable access logging for the load balancers. Logs are stored in the specified S3 bucket."
      required: true
      type: "boolean"
      default: false
    - variable: "ELBV2_ACCESS_LOGS_BUCKET"
      label: "Access Logs S3 Bucket"
      description: |
        The name of the S3 bucket to store the access logs in.
        It must be located in the same region as the load balancer and must have a bucket policy granting write permissions to ELB.
      type: "string"
      required: false
    - variable: "ELBV2_ACCESS_LOGS_PREFIX"
      label: "Access Logs S3 Bucket Prefix"
      description: "An optional bucket prefix. By default the logs are stored in the root of the S3 bucket."
      type: "string"
      required: false

awselbv2:
  health_check:
    port: 1000
    interval: 5000
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.0
    healthy_threshold: 2
    response_timeout: 2000
